# 스타벅스 매장 데이터 분석과 지도 시각화

In [2]:
from pathlib import Path
import pandas as pd 
import os

In [3]:
csv_path = Path("./Data/starbucks_all_stores.csv")

In [4]:
csv_path

WindowsPath('Data/starbucks_all_stores.csv')

In [6]:
df = pd.read_csv(csv_path)
df.shape

(2133, 137)

In [8]:
df.head()

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t30,t36,t27,t29,t43,t48,z9999,t64,t66,p02
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0
4,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,0

In [10]:
df.columns

Index(['seq', 'sido_cd', 'sido_nm', 'gugun_cd', 'gugun_nm', 'code_order',
       'view_yn', 'store_num', 'sido', 'gugun',
       ...
       't30', 't36', 't27', 't29', 't43', 't48', 'z9999', 't64', 't66', 'p02'],
      dtype='str', length=137)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2133 entries, 0 to 2132
Columns: 137 entries, seq to p02
dtypes: float64(71), int64(52), str(14)
memory usage: 2.2 MB

In [14]:
"sido" in df.columns

True

In [15]:
df["sido_name"].info()

<class 'pandas.Series'>
RangeIndex: 2133 entries, 0 to 2132
Series name: sido_name
Non-Null Count  Dtype
--------------  -----
2133 non-null   str
dtypes: str(1)
memory usage: 16.8 KB

In [25]:
#시도별 매장 수 집계
df.groupby("sido_name").agg(sido_count = ("sido_code", "count")).sort_values("sido_count", ascending=False)

           sido_count
sido_name
서울                683
경기                521
부산                146
대구                 95
인천                 93
경남                 81
대전                 73
광주                 71
경북                 64
충남                 55
전북                 44
충북                 41
전남                 38
제주                 35
울산                 34
강원                 29
세종                 16
강원도                14

In [26]:
# 구, 군 별 매장 수 집계 
df.groupby("gugun_name").agg(gugun_count = ("gugun_code", "count")).sort_values("gugun_count", ascending=False)

            gugun_count
gugun_name
강남구                 103
중구                   94
서구                   73
서초구                  59
영등포구                 45
...                 ...
영천시                   1
정읍시                   1
증평군                   1
평창군                   1
화순군                   1

[157 rows x 1 columns]

In [27]:
"type" in df.columns

False

In [28]:
df["s_name"][9]

'압구정R'

In [29]:
"R" in df["s_name"][9]

True

In [31]:
def store_type(x):
    type_name = ""
    if "R" in x:
        type_name ="R"
    elif "DT" in x:
        type_name = "DT"
    else: 
        type_name = "일반"
    return type_name

In [ ]:
store_type(df["s_name"][103])

'일반'

In [35]:
df["s_name"][102]

'강남세곡DT'

In [37]:
df["s_name"].apply(store_type)

0       일반
1       일반
2       일반
3       일반
4       일반
        ..
2128    DT
2129    일반
2130    일반
2131    DT
2132    일반
Name: s_name, Length: 2133, dtype: str

In [38]:
df["s_type"]  = df["s_name"].apply(store_type)
df.head(3)

C:\Users\6131\AppData\Local\Temp\ipykernel_17996\1236136921.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df["s_type"]  = df["s_name"].apply(store_type)

,seq,sido_cd,sido_nm,gugun_cd,gugun_nm,code_order,view_yn,store_num,sido,gugun,...,t36,t27,t29,t43,t48,z9999,t64,t66,p02,s_type
0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,일반
1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,일반
2,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,0,0,0,0,0,0,0,0,일반

In [39]:
# 매장 타입 별 집계 
df.groupby("s_type").agg(type_count = ("s_type", "count"))

        type_count
s_type
DT             512
R               60
일반            1561

In [40]:
df.groupby(["sido_name", "s_type"]).agg(type_count = ("s_type", "count"))

                  type_count
sido_name s_type
강원        DT              14
          R                2
          일반              13
강원도       DT               7
          일반               7
경기        DT             158
          R               16
          일반             347
경남        DT              31
          R                1
          일반              49
경북        DT              31
          일반              33
광주        DT              28
          일반              43
대구        DT              36
          R                2
          일반              57
대전        DT              17
          R                2
          일반              54
부산        DT              30
          R                2
          일반             114
서울        DT              24
          R               31
          일반             628
세종        DT               3
          R                1
          일반              12
울산        DT              16
          일반              18
인천        DT              24
          R                1
          일반              68
전남        DT              15
          일반              23
전북        DT              22
          일반              22
제주        DT              20
          R                2
          일반              13
충남        DT              22
          일반              33
충북        DT              14
          일반              27

In [41]:
# 2. lambda 식을 이용한 s_type 컬럼 생성
df['s_type'] = df['s_name'].apply(lambda x: 'R' if x.endswith('R') else ('DT' if x.endswith('DT') else '일반'))

# 지도 시각화 라이브러리

In [43]:
!uv pip install folium

Checked 1 package in 4ms

In [44]:
import folium

In [49]:
m = folium.Map(location=[36.5, 127.8], zoom_start=7)
popup = folium.Popup("서울 시청<br>서울특별시 중구 세종대로", max_width=250)

In [53]:
folium.Marker(
    location=[37.5665, 126.9780],
    popup = popup,
    tooltip = "서울시청점"
).add_to(m)

In [55]:
m.save("result_map.html")

In [57]:
m = folium.Map(location=[36.5, 127.8], zoom_start=7)

In [64]:
for _, row in df.iterrows():
    # 위도, 경도 : lat, lot 
    # 스토어 이름: s_name 
    # 스토어 주소: addr
    # 스토어 타입: s_type 
    print("위도경도: ", row["lat"], row["lot"])
    print("스토어 이름: ", row["s_name"])
    print("스토어 주소: ", row["addr"])
    print("스토어 타입: ", row["s_type"])
    popup_text = f"{row['s_name']},br.{row['addr']}<br>{row['s_type']}"
    popup = folium.Popup(popup_text, max_width=300)
    folium.Marker(
        location=[row["lat"], row["lot"]],
        popup = popup, 
        tooltip=row['s_name']
    ).add_to(m)

위도경도:  37.501087 127.043069
스토어 이름:  역삼아레나빌딩
스토어 주소:  서울특별시 강남구 역삼동 721-13 아레나빌딩
스토어 타입:  일반
위도경도:  37.510178 127.022223
스토어 이름:  논현역사거리
스토어 주소:  서울특별시 강남구 논현동 142-2 정일빌딩
스토어 타입:  일반
위도경도:  37.5139309 127.0206057
스토어 이름:  신사역성일빌딩
스토어 주소:  서울특별시 강남구 논현동 18-4 성일빌딩
스토어 타입:  일반
위도경도:  37.499517 127.031495
스토어 이름:  국기원사거리
스토어 주소:  서울특별시 강남구 역삼동 648-22 동찬빌딩
스토어 타입:  일반
위도경도:  37.494668 127.062583
스토어 이름:  대치재경빌딩
스토어 주소:  서울특별시 강남구 대치동 599 대원빌딩
스토어 타입:  일반
위도경도:  37.515 127.063196
스토어 이름:  봉은사역
스토어 주소:  서울특별시 강남구 삼성동 108-6 JBK TOWER 빌딩
스토어 타입:  일반
위도경도:  37.5227934 127.0286009
스토어 이름:  압구정윤성빌딩
스토어 주소:  서울특별시 강남구 신사동 592 윤성빌딩
스토어 타입:  일반
위도경도:  37.51015 127.060275
스토어 이름:  코엑스별마당
스토어 주소:  서울특별시 강남구 삼성동 159 코엑스
스토어 타입:  일반
위도경도:  37.50775 127.060651
스토어 이름:  삼성역섬유센터R
스토어 주소:  서울특별시 강남구 대치동 944-31 한국섬유산업연합회
스토어 타입:  R
위도경도:  37.5273669 127.033061
스토어 이름:  압구정R
스토어 주소:  서울특별시 강남구 신사동 621-1
스토어 타입:  R
위도경도:  37.48802242128887 127.10297991136235
스토어 이름:  수서역R
스토어 주소:  서울특별시 강남구 수서동 715 수서빌딩
스토어 타입:  R
위도경도:  37.485192 127.036685
스토어 이름:  양재강남빌딩R
스토어 주소:  서울특별시 강남구 도곡동 956 LG전자 강남R&D센터
스토어 타입:  R
위도경도:  37.505321 127.050409
스토어 이름:  선릉동신빌딩R
스토어 주소:  서울특별시 강남구 삼성동 141-28 동신빌딩
스토어 타입:  R
위도경도:  37.51131683405367 127.04846338902249
스토어 이름:  봉은사로선정릉
스토어 주소:  서울특별시 강남구 삼성동 114-9 올림푸스타워
스토어 타입:  일반
위도경도:  37.502117 127.026672
스토어 이름:  강남오거리
스토어 주소:  서울특별시 강남구 역삼동 813-17 1,2,3층
스토어 타입:  일반
위도경도:  37.50999 127.061455
스토어 이름:  스타필드코엑스몰R
스토어 주소:  서울특별시 강남구 삼성동 159 코엑스  A106호
스토어 타입:  R
위도경도:  37.51827133155829 127.04595951286774
스토어 이름:  강남구청정문
스토어 주소:  서울특별시 강남구 청담동 44-12 대륭빌딩
스토어 타입:  일반
위도경도:  37.492805 127.041309
스토어 이름:  도곡공원
스토어 주소:  서울특별시 강남구 역삼동 788-10
스토어 타입:  일반
위도경도:  37.497711 127.028439
스토어 이름:  강남R
스토어 주소:  서울특별시 강남구 역삼동 825 미진프라자 1층 101호
스토어 타입:  R
위도경도:  37.498973 127.060172
스토어 이름:  대치은마사거리
스토어 주소:  서울특별시 강남구 대치동 941-19 진흥빌딩
스토어 타입:  일반
위도경도:  37.52275803097751 127.05697488157423
스토어 이름:  청담영동대로
스토어 주소:  서울특별시 강남구 청담동 132-1 삼청빌딩
스토어 타입:  일반
위도경도:  37.526283 127.02956
스토어 이름:  압구정
스토어 주소:  서울특별시 강남구 신사동 609 이소니프라자
스토어 타입:  일반
위도경도:  37.521933 127.022521
스토어 이름:  신사가로수
스토어 주소:  서울특별시 강남구 신사동 533-11
스토어 타입:  일반
위도경도:  37.525216 127.041827
스토어 이름:  청담스타R
스토어 주소:  서울특별시 강남구 청담동 89-4
스토어 타입:  R
위도경도:  37.492396 127.03091
스토어 이름:  강남우성
스토어 주소:  서울특별시 강남구 역삼동 832-3 강남역 쉐르빌
스토어 타입:  일반
위도경도:  37.52247510377488 127.037947289408
스토어 이름:  학동사거리
스토어 주소:  서울특별시 강남구 논현2동 93-2번지
스토어 타입:  일반
위도경도:  37.503331 127.058817
스토어 이름:  대치사거리
스토어 주소:  서울특별시 강남구 대치동 960-5 티아빌딩
스토어 타입:  일반
위도경도:  37.5075307 127.05742710000004
스토어 이름:  포스코사거리
스토어 주소:  서울특별시 강남구 삼성동 157-36 화진빌딩
스토어 타입:  일반
위도경도:  37.5191632 127.0286446
스토어 이름:  을지병원사거리
스토어 주소:  서울특별시 강남구 논현동 59-8 구산빌딩
스토어 타입:  일반
위도경도:  37.5162021 127.0207428
스토어 이름:  신사역
스토어 주소:  서울특별시 강남구 논현동 1-3 렉스타워
스토어 타입:  일반
위도경도:  37.492167 127.057398
스토어 이름:  도곡역
스토어 주소:  서울특별시 강남구 대치동 651
스토어 타입:  일반
위도경도:  37.514887 127.035653
스토어 이름:  서울세관사거리
스토어 주소:  서울특별시 강남구 논현동 238-5 한국건설기술인협회
스토어 타입:  일반
위도경도:  37.5238436444947 127.04694995171084
스토어 이름:  청담사거리
스토어 주소:  서울특별시 강남구 청담동 6-5 리츠타워
스토어 타입:  일반
위도경도:  37.496801 127.055055
스토어 이름:  한티역
스토어 주소:  서울특별시 강남구 대치동 1024 디마크빌딩 101호
스토어 타입:  일반
위도경도:  37.49416922110828 127.03317791475052
스토어 이름:  역삼초교사거리
스토어 주소:  서울특별시 강남구 역삼동 830-71
스토어 타입:  일반
위도경도:  37.513715 127.059245
스토어 이름:  코엑스몰
스토어 주소:  서울특별시 강남구 삼성동 159 코엑스 O103호
스토어 타입:  일반
위도경도:  37.5231593 127.02162499999996
스토어 이름:  가로수길
스토어 주소:  서울특별시 강남구 신사동 529-10 1~2층
스토어 타입:  일반
위도경도:  37.501623 127.039375
스토어 이름:  역삼대로
스토어 주소:  서울특별시 강남구 역삼동 678-39번지 한국고등교육재단빌딩1층
스토어 타입:  일반
위도경도:  37.499721 127.033582
스토어 이름:  역삼포스코
스토어 주소:  서울특별시 강남구 역삼동 735-3번지 P&S TOWER
스토어 타입:  일반
위도경도:  37.50314 127.025546
스토어 이름:  강남대로
스토어 주소:  서울특별시 강남구 역삼동 809-10번지 한석타워 2층 1-2호
스토어 타입:  일반
위도경도:  37.5243631 127.05155990000004
스토어 이름:  청담
스토어 주소:  서울특별시 강남구 청담동 52-1 인희빌딩 1층
스토어 타입:  일반
위도경도:  37.507794 127.06517
스토어 이름:  삼성교
스토어 주소:  서울특별시 강남구 대치동 1001-8 외 2필지 동남유화빌딩1층
스토어 타입:  일반
위도경도:  37.51464884 127.0307302
스토어 이름:  학동역
스토어 주소:  서울특별시 강남구 논현동 87
스토어 타입:  일반
위도경도:  37.49966175 127.0622171
스토어 이름:  대치
스토어 주소:  서울특별시 강남구 대치동 988-17 대진빌딩
스토어 타입:  일반
위도경도:  37.490102006982106 127.05507020231974
스토어 이름:  신세계푸드마켓도곡
스토어 주소:  서울특별시 강남구 도곡동 467-17 타워팰리스Ⅱ F 지하1층
스토어 타입:  일반
위도경도:  37.50689645929321 127.0557187245366
스토어 이름:  삼성
스토어 주소:  서울특별시 강남구 삼성동 144-25 태리타워 1층
스토어 타입:  일반
위도경도:  37.50377562 127.051196
스토어 이름:  선릉세화빌딩
스토어 주소:  서울특별시 강남구 대치동 889-70 세화빌딩 1층
스토어 타입:  일반
위도경도:  37.52674095 127.0281105
스토어 이름:  압구정역
스토어 주소:  서울특별시 강남구 신사동 580-2 관영빌딩 1층 지하1층
스토어 타입:  일반
위도경도:  37.5268256687184 127.03477619379316
스토어 이름:  압구정로
스토어 주소:  서울특별시 강남구 신사동 635-13
스토어 타입:  일반
위도경도:  37.495890648099504 127.03890917851652
스토어 이름:  구역삼사거리
스토어 주소:  서울특별시 강남구 역삼동 747-21
스토어 타입:  일반
위도경도:  37.50236693 127.0407
스토어 이름:  큰길타워
스토어 주소:  서울특별시 강남구 역삼동 677-25 큰길타워
스토어 타입:  일반
위도경도:  37.5165849 127.04124330000002
스토어 이름:  강남구청역
스토어 주소:  서울특별시 강남구 논현동 241-7 웰빙센터 1층
스토어 타입:  일반
위도경도:  37.493554 127.061874
스토어 이름:  대치역
스토어 주소:  서울특별시 강남구 대치동 507 윈플러스상가 107호
스토어 타입:  일반
위도경도:  37.47781106 127.0451411
스토어 이름:  포이
스토어 주소:  서울특별시 강남구 개포4동 1229-1
스토어 타입:  일반
위도경도:  37.49971982 127.0349084
스토어 이름:  아크플레이스
스토어 주소:  서울특별시 강남구 역삼동 736-1
스토어 타입:  일반
위도경도:  37.49803646 127.0684943
스토어 이름:  학여울역
스토어 주소:  서울특별시 강남구 대치동 994-10
스토어 타입:  일반
위도경도:  37.51075489999999 127.04455970000004
스토어 이름:  선정릉역
스토어 주소:  서울특별시 강남구 삼성2동 37-17 에프오빌딩
스토어 타입:  일반
위도경도:  37.51350444312708 127.05273753314826
스토어 이름:  삼성현대힐
스토어 주소:  서울특별시 강남구 삼성동 51번지
스토어 타입:  일반
위도경도:  37.5018592 127.03727759999992
스토어 이름:  GS타워
스토어 주소:  서울특별시 강남구 역삼동 679
스토어 타입:  일반
위도경도:  37.523912710310015 127.02807214378778
스토어 이름:  압구정미소
스토어 주소:  서울특별시 강남구 신사동 583-3
스토어 타입:  일반
위도경도:  37.50393894 127.0485135
스토어 이름:  선릉역
스토어 주소:  서울특별시 강남구 역삼동 708-6 LG화재 빌딩
스토어 타입:  일반
위도경도:  37.515351 127.060109
스토어 이름:  코엑스사거리
스토어 주소:  서울특별시 강남구 삼성동 91-31
스토어 타입:  일반
위도경도:  37.492209 127.039389
스토어 이름:  역삼럭키
스토어 주소:  서울특별시 강남구 역삼동 798-30
스토어 타입:  일반
위도경도:  37.52809330107192 127.03652467188678
스토어 이름:  신압구정
스토어 주소:  서울특별시 강남구 신사동 639-7번지
스토어 타입:  일반
위도경도:  37.509013311862645 127.0403523996554
스토어 이름:  아크로힐스논현
스토어 주소:  서울특별시 강남구 역삼동 681번지 금강빌딩 1-2층
스토어 타입:  일반
위도경도:  37.4964557 127.02968850000002
스토어 이름:  강남비젼타워
스토어 주소:  서울특별시 강남구 역삼동 826-26번지 1층 101호
스토어 타입:  일반
위도경도:  37.526562559707806 127.04048346509586
스토어 이름:  압구정로데오역
스토어 주소:  서울특별시 강남구 청담동 84-3번지 삼원빌딩 1,2층
스토어 타입:  일반
위도경도:  37.50268239475304 127.04414328446828
스토어 이름:  르네상스사거리
스토어 주소:  서울특별시 강남구 역삼동 706-1번지
스토어 타입:  일반
위도경도:  37.50576457783876 127.05804488086115
스토어 이름:  포스코
스토어 주소:  서울특별시 강남구 대치동 942-5번지 1층
스토어 타입:  일반
위도경도:  37.50498118534617 127.0468080752464
스토어 이름:  선릉로
스토어 주소:  서울특별시 강남구 역삼동 697-45 대흥빌딩 1층
스토어 타입:  일반
위도경도:  37.511685 127.032187
스토어 이름:  논현힐탑
스토어 주소:  서울특별시 강남구 논현동 216-5번지
스토어 타입:  일반
위도경도:  37.51736229999999 127.02329570000006
스토어 이름:  도산가로수길
스토어 주소:  서울특별시 강남구 논현동 5번지 2층
스토어 타입:  일반
위도경도:  37.4859095 127.0452879
스토어 이름:  매봉역
스토어 주소:  서울특별시 강남구 도곡동 411-19 지앤지빌딩
스토어 타입:  일반
위도경도:  37.522514 127.035977
스토어 이름:  호림아트센터
스토어 주소:  서울특별시 강남구 신사동 651-24 호림아트센터 1빌딩
스토어 타입:  일반
위도경도:  37.51660207900788 127.0517527875551
스토어 이름:  청담역6번출구
스토어 주소:  서울특별시 강남구 삼성동 65-5, 65-10
스토어 타입:  일반
위도경도:  37.4730637068202 127.10244727289
스토어 이름:  강남자곡
스토어 주소:  서울특별시 강남구 자곡동 650, 107~109호
스토어 타입:  일반
위도경도:  37.50718 127.0631
스토어 이름:  삼성휘문
스토어 주소:  서울특별시 강남구 대치동 947-1
스토어 타입:  일반
위도경도:  37.4984818 127.052066
스토어 이름:  대치한티
스토어 주소:  서울특별시 강남구 대치동 922-1 SH타워
스토어 타입:  일반
위도경도:  37.4828551359882 127.0607152444621
스토어 이름:  개포동
스토어 주소:  서울특별시 강남구 개포동 167-9
스토어 타입:  일반
위도경도:  37.487400776036274 127.10292252273776
스토어 이름:  수서역사거리
스토어 주소:  서울특별시 강남구 수서동 724 로즈데일오피스텔
스토어 타입:  일반
위도경도:  37.513019 127.059838
스토어 이름:  코엑스아셈타워
스토어 주소:  서울특별시 강남구 삼성동 159 코엑스아셈타워 AT-01호
스토어 타입:  일반
위도경도:  37.5064031867752 127.031811320915
스토어 이름:  강남차여성병원
스토어 주소:  서울특별시 강남구 역삼동 605 마티네 차움
스토어 타입:  일반
위도경도:  37.50369465391196 127.04172081609173
스토어 이름:  센터필드R
스토어 주소:  서울특별시 강남구 역삼동 676 센터필드
스토어 타입:  R
위도경도:  37.51966 127.0341
스토어 이름:  도산사거리
스토어 주소:  서울특별시 강남구 논현동 70-6 트리스빌딩
스토어 타입:  일반
위도경도:  37.467274319644 127.099929726
스토어 이름:  강남세곡
스토어 주소:  서울특별시 강남구 세곡동 551 팜모드빌딩
스토어 타입:  일반
위도경도:  37.500313 127.066961
스토어 이름:  대치삼성
스토어 주소:  서울특별시 강남구 대치동 993-1
스토어 타입:  일반
위도경도:  37.4904345093246 127.033626302083
스토어 이름:  강남아이퀘스트
스토어 주소:  서울특별시 강남구 역삼동 839-16 아우디 도곡로 전시장
스토어 타입:  일반
위도경도:  37.507975 127.036478
스토어 이름:  언주역
스토어 주소:  서울특별시 강남구 역삼동 652-2
스토어 타입:  일반
위도경도:  37.4964928018315 127.052199273657
스토어 이름:  한티역8번출구
스토어 주소:  서울특별시 강남구 역삼동 765-17
스토어 타입:  일반
위도경도:  37.5058769838995 127.02428948306
스토어 이름:  신논현역3번출구
스토어 주소:  서울특별시 강남구 논현동 199 대남빌딩
스토어 타입:  일반
위도경도:  37.49993577 127.03684778
스토어 이름:  강남파이낸스센터
스토어 주소:  서울특별시 강남구 역삼동 737 강남파이낸스센터, 1층 B호
스토어 타입:  일반
위도경도:  37.4970572543978 127.028180714381
스토어 이름:  강남역신분당역사
스토어 주소:  서울특별시 강남구 역삼동 858
스토어 타입:  일반
위도경도:  37.509281 127.065563
스토어 이름:  삼성역
스토어 주소:  서울특별시 강남구 대치동 996-1번지
스토어 타입:  일반
위도경도:  37.50383 127.04487
스토어 이름:  테헤란로아남타워
스토어 주소:  서울특별시 강남구 역삼동 702-10 아남타워빌딩
스토어 타입:  일반
위도경도:  37.5078978596254 127.023338614644
스토어 이름:  강남논현
스토어 주소:  서울특별시 강남구 논현동 164-7
스토어 타입:  일반
위도경도:  37.510843366121534 127.06363342044264
스토어 이름:  삼성동
스토어 주소:  서울특별시 강남구 삼성동 168-22 페코빌딩
스토어 타입:  일반
위도경도:  37.525547584913184 127.03775087135216
스토어 이름:  리저브도산
스토어 주소:  서울특별시 강남구 신사동 656-4, 1,2층
스토어 타입:  일반
위도경도:  37.52575281715033 127.02886190444627
스토어 이름:  압구정역사3번출구
스토어 주소:  서울특별시 강남구 신사동 603 ANdAZ 지하1층
스토어 타입:  일반
위도경도:  37.5194407323478 127.049552661542
스토어 이름:  청담역
스토어 주소:  서울특별시 강남구 청담동 47-2
스토어 타입:  일반
위도경도:  37.52521971236768 127.0256601858147
스토어 이름:  압구정현대아파트
스토어 주소:  서울특별시 강남구 신사동 574-4
스토어 타입:  일반
위도경도:  37.517887 127.041375
스토어 이름:  강남청담빌딩
스토어 주소:  서울특별시 강남구 청담동 41 청담빌딩
스토어 타입:  일반
위도경도:  37.4991914625768 127.028204360257
스토어 이름:  케이스퀘어강남
스토어 주소:  서울특별시 강남구 역삼동 819
스토어 타입:  일반
위도경도:  37.466993809277 127.118330806807
스토어 이름:  강남세곡DT
스토어 주소:  서울특별시 강남구 세곡동 21-3, 21-1, 21-10(일부)
스토어 타입:  DT
위도경도:  37.618319 127.021072
스토어 이름:  미아뉴타운
스토어 주소:  서울특별시 강북구 미아동 812-2 행전빌딩
스토어 타입:  일반
위도경도:  37.639987861152015 127.0274331199793
스토어 이름:  강북구청사거리
스토어 주소:  서울특별시 강북구 수유동 174-13
스토어 타입:  일반
위도경도:  37.611831247629375 127.03058552434908
스토어 이름:  미아사거리역
스토어 주소:  서울특별시 강북구 미아동 35-30
스토어 타입:  일반
위도경도:  37.6380167 127.02613500000008
스토어 이름:  수유역
스토어 주소:  서울특별시 강북구 번동 418-17
스토어 타입:  일반
위도경도:  37.626148 127.026578
스토어 이름:  미아역
스토어 주소:  서울특별시 강북구 미아동 121-19번지
스토어 타입:  일반
위도경도:  37.636722675028174 127.02332208832507
스토어 이름:  수유역5번출구
스토어 주소:  서울특별시 강북구 수유동 740 에피소드 수유 838
스토어 타입:  일반
위도경도:  37.66419549576315 127.01040728594248
스토어 이름:  서울안토
스토어 주소:  서울특별시 강북구 우이동 산14-3
스토어 타입:  일반
위도경도:  37.558509 126.835096
스토어 이름:  발산역사거리
스토어 주소:  서울특별시 강서구 마곡동 801-2
스토어 타입:  일반
위도경도:  37.559611 126.826298
스토어 이름:  마곡역
스토어 주소:  서울특별시 강서구 마곡동 798-3
스토어 타입:  일반
위도경도:  37.549510038804 126.8360616480306
스토어 이름:  우장산역
스토어 주소:  서울특별시 강서구 내발산동 719-6 송화쇼핑센터
스토어 타입:  일반
위도경도:  37.5605261 126.833887
스토어 이름:  마곡사이언스타워R
스토어 주소:  서울특별시 강서구 마곡동 796-3 마곡사이언스타워
스토어 타입:  R
위도경도:  37.574456834773024 126.8164881237982
스토어 이름:  방화DT
스토어 주소:  서울특별시 강서구 방화동 293-4, 293-14, 293-15
스토어 타입:  DT
위도경도:  37.56813 126.82614
스토어 이름:  마곡나루역
스토어 주소:  서울특별시 강서구 마곡동 759-3 보타닉파크타워Ⅰ105,203,204호
스토어 타입:  일반
위도경도:  37.560487 126.829667
스토어 이름:  마곡GMG
스토어 주소:  서울특별시 강서구 마곡동 773-2 마곡지엠지타워
스토어 타입:  일반
위도경도:  37.56164 126.853327
스토어 이름:  가양역
스토어 주소:  서울특별시 강서구 등촌동 73-1 금부빌딩
스토어 타입:  일반
위도경도:  37.5350107501795 126.86318804786
스토어 이름:  화곡DT
스토어 주소:  서울특별시 강서구 화곡동 772-67
스토어 타입:  DT
위도경도:  37.54061901972644 126.83738800870792
스토어 이름:  화곡동
스토어 주소:  서울특별시 강서구 화곡동 1073-10
스토어 타입:  일반
위도경도:  37.547359 126.874436
스토어 이름:  염창역
스토어 주소:  서울특별시 강서구 염창동 282-23
스토어 타입:  일반
위도경도:  37.56033524296544 126.83913908184506
스토어 이름:  발산역
스토어 주소:  서울특별시 강서구 등촌동 678-14 그랜드마트
스토어 타입:  일반
위도경도:  37.5323235082489 126.84612332664445
스토어 이름:  까치산역
스토어 주소:  서울특별시 강서구 화곡동 343-1번지
스토어 타입:  일반
위도경도:  37.5653031840314 126.82570428625807
스토어 이름:  마곡코엑스
스토어 주소:  서울특별시 강서구 마곡동 767, 르웨스트시티 제본동 제1층 샵4/5호
스토어 타입:  일반
위도경도:  37.5485479128966 126.878259347206
스토어 이름:  염창대로
스토어 주소:  서울특별시 강서구 염창동 260, 101호
스토어 타입:  일반
위도경도:  37.5579224739977 126.84054030692
스토어 이름:  발산역5번출구
스토어 주소:  서울특별시 강서구 내발산동 647 DH647, 1층 일부
스토어 타입:  일반
위도경도:  37.56785182406142 126.84082079898184
스토어 이름:  양천향교역
스토어 주소:  서울특별시 강서구 마곡동 776-2 마곡센트럴대방디엠시티오피스텔 121-1 121-2호
스토어 타입:  일반
위도경도:  37.54227920628 126.839299954553
스토어 이름:  화곡역8번출구
스토어 주소:  서울특별시 강서구 화곡동 1051-22, 1층 일부
스토어 타입:  일반
위도경도:  37.54661114997271 126.83611326062484
스토어 이름:  강서우장산
스토어 주소:  서울특별시 강서구 화곡동 1013-3 우장산역 해링턴 타워, 116/117/118/119/120호
스토어 타입:  일반
위도경도:  37.5504921817371 126.8665095756118
스토어 이름:  등촌대로
스토어 주소:  서울특별시 강서구 염창동 274-17 센터스퀘어
스토어 타입:  일반
위도경도:  37.56910032273387 126.83633283391288
스토어 이름:  마곡보타닉게이트
스토어 주소:  서울특별시 강서구 마곡동 779
스토어 타입:  일반
위도경도:  37.56007 126.855372
스토어 이름:  가양역사거리
스토어 주소:  서울특별시 강서구 등촌동 628-9 가양더스카이벨리5차 지식산업센터 101, 102, 114,~117호
스토어 타입:  일반
위도경도:  37.56124715192089 126.82465548376592
스토어 이름:  원그로브
스토어 주소:  서울특별시 강서구 마곡동769 WB115호
스토어 타입:  일반
위도경도:  37.55467 126.83672
스토어 이름:  내발산
스토어 주소:  서울특별시 강서구 내발산동 668, 101/102호
스토어 타입:  일반
위도경도:  37.5671428910102 126.825315150636
스토어 이름:  마곡웰튼
스토어 주소:  서울특별시 강서구 마곡동 759-2, 104/105/106호
스토어 타입:  일반
위도경도:  37.55912618463173 126.80239253168018
스토어 이름:  김포공항국내선
스토어 주소:  서울특별시 강서구 공항동 1373-5 김포공항 국내선터미널 3층
스토어 타입:  일반
위도경도:  37.56627942080141 126.8060664470359
스토어 이름:  김포공항DT
스토어 주소:  서울특별시 강서구 방화동 645-6
스토어 타입:  DT
위도경도:  37.55978002533287 126.83998346498424
스토어 이름:  강서NC
스토어 주소:  서울특별시 강서구 등촌동 689 엔씨백화점 1F, 일부
스토어 타입:  일반
위도경도:  37.56604490355177 126.80050380500948
스토어 이름:  김포공항국제선
스토어 주소:  서울특별시 강서구 방화동 886 (면세구역 내 35번 게이트 옆)
스토어 타입:  일반
위도경도:  37.56237450098008 126.82693066365748
스토어 이름:  마곡케이스퀘어
스토어 주소:  서울특별시 강서구 마곡동 768-1, 1층 일부
스토어 타입:  일반
위도경도:  37.567007 126.822246
스토어 이름:  마곡나루공원
스토어 주소:  서울특별시 강서구 마곡동 743-1
스토어 타입:  일반
위도경도:  37.56105570786667 126.81150987871888
스토어 이름:  송정역
스토어 주소:  서울특별시 강서구 공항동 32-3, 1층 일부
스토어 타입:  일반
위도경도:  37.5549266 126.8523133
스토어 이름:  강서구청사거리
스토어 주소:  서울특별시 강서구 화곡동 1111 SJ라벨라
스토어 타입:  일반
위도경도:  37.47776012993906 126.96114261955483
스토어 이름:  낙성대역
스토어 주소:  서울특별시 관악구 봉천동 1660-1
스토어 타입:  일반
위도경도:  37.47932480888598 126.95270199623683
스토어 이름:  관악서울대입구R
스토어 주소:  서울특별시 관악구 봉천동 856-6 BS타워
스토어 타입:  R
위도경도:  37.480935 126.908407
스토어 이름:  신림DT
스토어 주소:  서울특별시 관악구 신림동 564-12, 564-11
스토어 타입:  DT
위도경도:  37.48166265091104 126.9520164977362
스토어 이름:  서울대역
스토어 주소:  서울특별시 관악구 봉천동 861-6
스토어 타입:  일반
위도경도:  37.476243169019526 126.96511724631266
스토어 이름:  낙성대DT
스토어 주소:  서울특별시 관악구 봉천동 1657-3
스토어 타입:  DT
위도경도:  37.4760559 126.980928
스토어 이름:  사당
스토어 주소:  서울특별시 관악구 남현동 1060-10
스토어 타입:  일반
위도경도:  37.491449 126.925432
스토어 이름:  보라매대교빌딩
스토어 주소:  서울특별시 관악구 봉천동 729-21 대교타워 1층
스토어 타입:  일반
위도경도:  37.48609493 126.9291602
스토어 이름:  신림
스토어 주소:  서울특별시 관악구 신림동 1432-71번지
스토어 타입:  일반
위도경도:  37.48407101920536 126.93025831103375
스토어 이름:  신림타임스트림
스토어 주소:  서울특별시 관악구 신림동 1641-2번지 타임스트림 1층
스토어 타입:  일반
위도경도:  37.481207389699065 126.95140060487287
스토어 이름:  서울대입구역
스토어 주소:  서울특별시 관악구 봉천동 869-1
스토어 타입:  일반
위도경도:  37.470488195804656 126.9381586560584
스토어 이름:  신림녹두거리
스토어 주소:  서울특별시 관악구 신림동 1747 센터스퀘어 서울대점
스토어 타입:  일반
위도경도:  37.4812061 126.9536942
스토어 이름:  서울대입구역8번출구
스토어 주소:  서울특별시 관악구 봉천동 852-5
스토어 타입:  일반
위도경도:  37.4820375340064 126.942287792538
스토어 이름:  봉천역
스토어 주소:  서울특별시 관악구 봉천동 927-5 청운빌딩
스토어 타입:  일반
위도경도:  37.48665266827689 126.94829614696478
스토어 이름:  봉천현대시장
스토어 주소:  서울특별시 관악구 봉천동 465-2, 1층 101~104호
스토어 타입:  일반
위도경도:  37.4771331 126.9641468
스토어 이름:  낙성대역7번출구
스토어 주소:  서울특별시 관악구 봉천동 1687-13, 1687-14 더블유타워 1층 일부
스토어 타입:  일반
위도경도:  37.5415474727422 127.07115584769804
스토어 이름:  건국대
스토어 주소:  서울특별시 광진구 화양동 5-45
스토어 타입:  일반
위도경도:  37.551946 127.076404
스토어 이름:  어린이대공원역
스토어 주소:  서울특별시 광진구 군자동 236
스토어 타입:  일반
위도경도:  37.55062116262961 127.09003207951665
스토어 이름:  아차산역
스토어 주소:  서울특별시 광진구 구의동 75-19
스토어 타입:  일반
위도경도:  37.541129 127.09524
스토어 이름:  올림픽대교북단
스토어 주소:  서울특별시 광진구 구의동 200-2
스토어 타입:  일반
위도경도:  37.54529838924125 127.0871967283424
스토어 이름:  구의DT
스토어 주소:  서울특별시 광진구 구의동 67-36,37,7
스토어 타입:  DT
위도경도:  37.5371158 127.0825821
스토어 이름:  자양사거리
스토어 주소:  서울특별시 광진구 자양동 779
스토어 타입:  일반
위도경도:  37.557026068940765 127.07910984029934
스토어 이름:  군자역
스토어 주소:  서울특별시 광진구 군자동 478-5 중앙빌딩
스토어 타입:  일반
위도경도:  37.5473711178786 127.106048727555
스토어 이름:  광나루
스토어 주소:  서울특별시 광진구 광장동 329-1 1,2층
스토어 타입:  일반
위도경도:  37.538544 127.073009
스토어 이름:  건대스타시티
스토어 주소:  서울특별시 광진구 자양동 227-7  1층 19,20,21호
스토어 타입:  일반
위도경도:  37.5406604 127.0707225
스토어 이름:  건대입구
스토어 주소:  서울특별시 광진구 화양동 5-47
스토어 타입:  일반
위도경도:  37.54261257747251 127.09964053100875
스토어 이름:  광장
스토어 주소:  서울특별시 광진구 광장동 582
스토어 타입:  일반
위도경도:  37.538466 127.071271
스토어 이름:  건국클래식
스토어 주소:  서울특별시 광진구 자양동 227-342 더 클래식500  1층 C102,103호
스토어 타입:  일반
위도경도:  37.5407966413791 127.066728885927
스토어 이름:  건대로데오
스토어 주소:  서울특별시 광진구 자양동 8-8 더포디엄830
스토어 타입:  일반
위도경도:  37.53474180652488 127.0919731720276
스토어 이름:  강변
스토어 주소:  서울특별시 광진구 구의동 594-4 금성빌딩
스토어 타입:  일반
위도경도:  37.53657397133724 127.08785695168248
스토어 이름:  구의역이스트폴
스토어 주소:  서울특별시 광진구 자양동 870, 1층
스토어 타입:  일반
위도경도:  37.54603056145237 127.07381934747976
스토어 이름:  건대후문
스토어 주소:  서울특별시 광진구 화양동 111-12 빌리브 인테라스 B02~B06
스토어 타입:  일반
위도경도:  37.56505700511581 127.08445231025853
스토어 이름:  중곡역
스토어 주소:  서울특별시 광진구 중곡동 30-80 보건복지행정타운 1층일부
스토어 타입:  일반
위도경도:  37.5386200465941 127.07348956991508
스토어 이름:  자양이마트
스토어 주소:  서울특별시 광진구 자양동 227-7 더샵스타시티 지하1층
스토어 타입:  일반
위도경도:  37.532684640479 127.067878503557
스토어 이름:  자양역
스토어 주소:  서울특별시 광진구 자양동 855 이튼타워리버3차 1층 109호
스토어 타입:  일반
위도경도:  37.54914275025103 127.07502761108316
스토어 이름:  세종대
스토어 주소:  서울특별시 광진구 군자동 98 세종대학교
스토어 타입:  일반
위도경도:  37.52833825339653 127.06827256457495
스토어 이름:  뚝섬한강공원
스토어 주소:  서울특별시 광진구 자양동 424
스토어 타입:  일반
위도경도:  37.537063 127.085053
스토어 이름:  구의역
스토어 주소:  서울특별시 광진구 구의동 683, 101호
스토어 타입:  일반
위도경도:  37.54774853077512 127.07126924540049
스토어 이름:  화양삼거리
스토어 주소:  서울특별시 광진구 화양동 174 건대 트레비앙 오피스텔
스토어 타입:  일반
위도경도:  37.55769507399991 127.079087912222
스토어 이름:  군자사거리
스토어 주소:  서울특별시 광진구 중곡동 649-4 1층
스토어 타입:  일반
위도경도:  37.45588672536701 126.89568245942294
스토어 이름:  금천구청역
스토어 주소:  서울특별시 금천구 시흥동 1031, 엠메디컬타워 1층
스토어 타입:  일반
위도경도:  37.48082408602027 126.88100079322535
스토어 이름:  가산에스케이
스토어 주소:  서울특별시 금천구 가산동 371-41, SK V1센터 1층
스토어 타입:  일반
위도경도:  37.47158263368701 126.8986055180454
스토어 이름:  독산사거리
스토어 주소:  서울특별시 금천구 독산동 159-23 영진빌딩
스토어 타입:  일반
위도경도:  37.44875938266414 126.9032387598192
스토어 이름:  금천시흥
스토어 주소:  서울특별시 금천구 시흥동 904-22 더플레이스
스토어 타입:  일반
위도경도:  37.48135375445197 126.88358906045958
스토어 이름:  가산디지털단지역
스토어 주소:  서울특별시 금천구 가산동 50-3, 대륭포스트타워 6차 1층
스토어 타입:  일반
위도경도:  37.46957081 126.89565779
스토어 이름:  금천독산
스토어 주소:  서울특별시 금천구 독산동 291-1
스토어 타입:  일반
위도경도:  37.479970085901 126.882507193785
스토어 이름:  가산디지털
스토어 주소:  서울특별시 금천구 가산동 371-28, 우림라이온스밸리 B동 1층
스토어 타입:  일반
위도경도:  37.47860691180926 126.88484825777417
스토어 이름:  마리오아울렛
스토어 주소:  서울특별시 금천구 가산동 60-20 ㈜마리오 3관1층
스토어 타입:  일반
위도경도:  37.47700409645337 126.88355058577784
스토어 이름:  가산브이타워
스토어 주소:  서울특별시 금천구 가산동 371-37, V-TOWER 1층
스토어 타입:  일반
위도경도:  37.46770966619833 126.88767404102676
스토어 이름:  독산역
스토어 주소:  서울특별시 금천구 가산동 673, 107-2, 1층
스토어 타입:  일반
위도경도:  37.4586898489368 126.896999968363
스토어 이름:  금천금나래
스토어 주소:  서울특별시 금천구 시흥동 113 1층
스토어 타입:  일반
위도경도:  37.47574363470601 126.88684803652212
스토어 이름:  가산퍼블릭
스토어 주소:  서울특별시 금천구 가산동 60-26, B동 F Park 1층
스토어 타입:  일반
위도경도:  37.477680443 126.888840553
스토어 이름:  가산현대아울렛
스토어 주소:  서울특별시 금천구 가산동 60-8 현대시티아울렛 가산점, 1층 일부
스토어 타입:  일반
위도경도:  37.48089352069766 126.88515566597012
스토어 이름:  가산케이에스
스토어 주소:  서울특별시 금천구 가산동 60-14, 가산KS타워 1층
스토어 타입:  일반
위도경도:  37.4800231711237 126.878250987906
스토어 이름:  가산어반워크
스토어 주소:  서울특별시 금천구 가산동 451-1
스토어 타입:  일반
위도경도:  37.6295 127.0574
스토어 이름:  월계역
스토어 주소:  서울특별시 노원구 월계동 633-31(104,105,106호)
스토어 타입:  일반
위도경도:  37.62759526807756 127.06190614033676
스토어 이름:  월계트레이더스
스토어 주소:  서울특별시 노원구 월계동 333-1 월계이마트
스토어 타입:  일반
위도경도:  37.656776 127.066442
스토어 이름:  상계초교사거리
스토어 주소:  서울특별시 노원구 상계동 372-16
스토어 타입:  일반
위도경도:  37.6206884 127.0743116
스토어 이름:  공릉DT
스토어 주소:  서울특별시 노원구 공릉동 597-34, 597-30, 597-31, 597-32, 597-33
스토어 타입:  DT
위도경도:  37.6610890700127 127.05801543641188
스토어 이름:  노원마들역

In [65]:
m.save("result_map.html")